name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Scala with JDK 11
      uses: olafurpg/setup-scala@v14
      with:
        java-version: openjdk@1.11
    - name: Formatting
      run: sbt clean fmt-format
    - name: Documentation
      run: sbt clean doc
